---
title: "Data Manipulation"
output: github_document
---

```{r}
library(tidyverse)
```

## Load in the FAS Litters Data

```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv", na = c("NA", ".", ""))
litters_df = janitor::clean_names(litters_df)
```

## `select`

Choose some other columns and not others.

```{r}
# specify the columns you want to keep.

select(litters_df, group, litter_number, gd0_weight)
```

```{r}
# specify a range of columns. `:`是范围的意思

select(litters_df, group, gd0_weight:gd_of_birth)
```

```{r}
# Don't want any columns. Remove it

select(litters_df, -litter_number)
```

Renaming columns ...

`select`只改变某列，其他不显示。`rename`其他列显示并且不变

```{r}
# Type 1.

select(litters_df, GROUP = group, LiTtEr_NuMbEr = litter_number)
```

```{r}
# Type 2. Use `rename()`
# rename the variables you care about, and keep everything else.

rename(litters_df, GROUP = group, LiTtEr_NuMbEr = litter_number)
```

```{r}
# 选择所有列名以 "gd" 开头的列

select(litters_df, starts_with("gd"))
```

```{r}
#把`litter_number`列放在最前面，其他列顺序不变

select(litters_df, litter_number, everything())
```

```{r}
#和上边的作用相同，只不过换成了`relocate()`

relocate(litters_df, litter_number)
```

## `filter` 详细筛选

```{r}
filter(litters_df, gd0_weight < 22)
filter(litters_df, gd0_weight >= 22)
```

```{r}
#必须两个等于号
filter(litters_df, gd_of_birth == 20)
```

```{r}
#去除等于20的行，展示剩下的
filter(litters_df, gd_of_birth != 20) 
```
or
```{r}
filter(litters_df, !(gd_of_birth == 20)) 
```


```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Mod8")
```

```{r}
# `%in%`是一个集合运算符
# 只保留 group 等于 "Con7" 和 "Con8" 的行

filter(litters_df, group %in% c("Con7", "Mod8"))
```

## `mutate`
modify col or create new ones.

```{r}
#group = str_to_lower(group)：把 group 这一列里的内容全部转成小写，并重新赋值给 group
#新建一个col:wt_gain

mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

## `arrange`
arrange() 是 dplyr 用来 排序 的函数。默认是升序排列。

```{r}
#给pups_born_alive排序，升序

arrange(litters_df, pups_born_alive)
```

```{r}
#在pups_born_alive升序的基础上，给gd0_weight排序，也是升序

arrange(litters_df, pups_born_alive, gd0_weight)
```


## `|>`
* 快捷键是“shift+ctrl+m”
* 嵌套函数调用
* 都不用写前面的“litters_df,”，直接写函数的后半部分就行
* janitor::clean_names()：括号里正常是"litters_df"，省略掉
* `drop_na(wt_gain)`：去掉含有缺失值 (NA) 的行

```{r}
litters_df = 
  read_csv("./data_import_examples/FAS_litters.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  select(-pups_survive) |> 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) |> 
  drop_na(wt_gain) 

litters_df
```

