---
title: "Data Import"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

## Read in some data 

Read in the litters dataset.

```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
names(litters_df)
```

 
## Take a look at the data

printing in the console.

```{r}
#读取整个litters数据

litters_df
```

```{r}
#取最后面的5行

tail(litters_df, 5)
```

```{r}
#取前面5行
#(View/ view、str、 head和tail)

head(litters_df, 5)
```

Sometimes skimming data is neat?
####快速浏览数据，观察是否异常
```{r}
skimr::skim(litters_df)
```

## fix the missingness
```{r}
litters_df = 
  read_csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", ""))
```

```{r}
#再次浏览

skimr::skim(litters_df)
```


```{r}
litters_df = 
    read_csv(file = "./data_import_examples/FAS_litters.csv",
        na = c(".", "NA", ""),
    col_types = cols(
      Group = col_factor()
    )
)

head(litters_df)
```

## Import Pups data

```{r}
pups_df = 
  read_csv(
    "data_import_examples/FAS_pups.csv",
    skip = 3,
    na = c("NA", ".", "")
  )

pups_df = 
  janitor::clean_names(pups_df)
```

## Other file formats

#### excel file 
```{r}
mlb_df = read_excel("./data_import_examples/mlb11.xlsx")
mlb_df
```

if the file is very large, we can use `n_max = 20` to read several cols.


#### Import LotR word counts.

```{r}
fotr_df =
  read_excel("./data_import_examples/LotR_Words.xlsx", range = "B3:D6")

fotr_df
```

Read in a SAS file.

```{r}
pulse_df = read_sas("./data_import_examples/public_pulse_data.sas7bdat")
pulse_df
head(pulse_df, 5)
```

